title: "Vân Anh Phonetics Lab"

description: "Japanese Phonetics • Vietnamese Phonetics"

theme: just-the-docs

url: "https://vananhlehosei.github.io"

color_scheme: light

search_enabled: true

heading_anchors: true
